#!/usr/bin/env bash
set -euo pipefail

export GH_PAGER=""

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------
missing=()
for cmd in base64 gh git mktemp; do
  command -v "${cmd}" >/dev/null 2>&1 || missing+=("${cmd}")
done
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "Error: missing required commands: ${missing[*]}" >&2
  exit 1
fi

trap 'echo -e "\nInterrupted. State may be incomplete — re-run to resume." >&2; exit 130' INT TERM

# --- BEGIN SCRIPT HASHES (auto-generated by scripts/generate-hashes.sh) ---
HASH_place_template_files="679e95af510cbf9c83212ab43bb17a79a7c5d3136b7d54f69f5ffe53ad55abfd"
HASH_sync_actions_settings="6f81b3b7ca653a369a567575184d06769d789d4103db77e2e72acc51c862339f"
# --- END SCRIPT HASHES ---

usage() {
  cat <<'EOF'
Usage: setup.sh [--only-actions-settings] [--overwrite-workflows] [--overwrite-renovate]

Options:
  --only-actions-settings Run only GitHub Actions permission settings sync.
  --skip-actions-settings Skip GitHub Actions permission settings.
  --overwrite-workflows  Overwrite existing workflow files.
  --overwrite-renovate   Overwrite an existing .github/renovate.json.
  -h, --help             Show this help.
EOF
}

ONLY_ACTIONS_SETTINGS=false
SKIP_ACTIONS_SETTINGS=false
OVERWRITE_WORKFLOWS=false
OVERWRITE_RENOVATE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
  --only-actions-settings)
    ONLY_ACTIONS_SETTINGS=true
    shift
    ;;
  --skip-actions-settings)
    SKIP_ACTIONS_SETTINGS=true
    shift
    ;;
  --overwrite-workflows)
    OVERWRITE_WORKFLOWS=true
    shift
    ;;
  --overwrite-renovate)
    OVERWRITE_RENOVATE=true
    shift
    ;;
  -h | --help)
    usage
    exit 0
    ;;
  -*)
    echo "Unknown option: $1" >&2
    usage >&2
    exit 1
    ;;
  *)
    echo "Error: setup.sh does not accept a repository argument. Run it from the target repository root." >&2
    usage >&2
    exit 1
    ;;
  esac
done

if [[ "${ONLY_ACTIONS_SETTINGS}" == true && "${SKIP_ACTIONS_SETTINGS}" == true ]]; then
  echo "Error: --only-actions-settings cannot be combined with --skip-actions-settings." >&2
  exit 1
fi

CURRENT_DIR=$(pwd -P)
TARGET_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || true)
if [[ -z "${TARGET_ROOT}" || "${CURRENT_DIR}" != "${TARGET_ROOT}" ]]; then
  echo "Error: run setup.sh from the target repository root." >&2
  exit 1
fi

if base64 --decode >/dev/null 2>&1 <<<""; then
  _BASE64_DECODE_FLAG="--decode"
else
  _BASE64_DECODE_FLAG="-D"
fi

decode_base64() {
  base64 "${_BASE64_DECODE_FLAG}"
}

download_provider_file() {
  local path="$1"
  gh api "repos/shuymn/github-actions/contents/${path}?ref=${PROVIDER_REF}" -q '.content' | decode_base64
}

resolve_target_repo() {
  local remote_url slug
  remote_url=$(git -C "${TARGET_ROOT}" remote get-url origin 2>/dev/null || true)
  if [[ -z "${remote_url}" ]]; then
    echo "Error: target repository must have an origin remote." >&2
    exit 1
  fi

  case "${remote_url}" in
  git@github.com:*)
    slug="${remote_url#git@github.com:}"
    ;;
  ssh://git@github.com/*)
    slug="${remote_url#ssh://git@github.com/}"
    ;;
  https://github.com/*)
    slug="${remote_url#https://github.com/}"
    ;;
  *)
    echo "Error: target repository origin must point to github.com." >&2
    exit 1
    ;;
  esac

  slug="${slug%.git}"
  slug="${slug%/}"
  if [[ ! "${slug}" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]]; then
    echo "Error: could not derive OWNER/REPO from origin remote." >&2
    exit 1
  fi

  gh api "repos/${slug}" -q '.full_name'
}

verify_script_hash() {
  local script_name="$1" file="$2"
  local expected actual
  case "${script_name}" in
  place-template-files.sh) expected="${HASH_place_template_files}" ;;
  sync-actions-settings.sh) expected="${HASH_sync_actions_settings}" ;;
  *)
    echo "Error: no known hash for ${script_name}" >&2
    exit 1
    ;;
  esac
  actual=$(shasum -a 256 "${file}" | cut -d' ' -f1)
  if [[ "${actual}" != "${expected}" ]]; then
    echo "Error: hash mismatch for ${script_name}" >&2
    echo "  expected: ${expected}" >&2
    echo "  actual:   ${actual}" >&2
    echo "This may indicate that PROVIDER_REF resolved to a different version than this setup.sh." >&2
    exit 1
  fi
}

run_repo_script() {
  local script_name="$1"
  shift

  (
    tmp_script=$(mktemp)
    trap 'rm -f "${tmp_script}"' EXIT
    download_provider_file "scripts/${script_name}" >"${tmp_script}"
    verify_script_hash "${script_name}" "${tmp_script}"
    chmod +x "${tmp_script}"
    "${tmp_script}" "$@"
  )
}

resolve_target_repo >/dev/null
PROVIDER_REF=$(gh api repos/shuymn/github-actions/commits/main -q .sha)

if [[ "${ONLY_ACTIONS_SETTINGS}" == true ]]; then
  run_repo_script "sync-actions-settings.sh" "${TARGET_ROOT}"
  echo "Done."
  exit 0
fi

place_args=("${TARGET_ROOT}" "${PROVIDER_REF}")
if [[ "${OVERWRITE_WORKFLOWS}" == true ]]; then
  place_args+=(--overwrite-workflows)
fi
if [[ "${OVERWRITE_RENOVATE}" == true ]]; then
  place_args+=(--overwrite-renovate)
fi
run_repo_script "place-template-files.sh" "${place_args[@]}"

if [[ "${SKIP_ACTIONS_SETTINGS}" == true ]]; then
  echo "Skipping GitHub Actions permission settings."
else
  run_repo_script "sync-actions-settings.sh" "${TARGET_ROOT}"
fi

echo "Done."
