name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: bin
          key: shell-linters-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Makefile') }}

      - name: Check generated setup.sh
        run: |
          make generate
          git diff --no-patch --exit-code setup.sh
        shell: bash

      - name: Run shell linters
        env:
          GH_TOKEN: ${{ github.token }}
        run: make lint-shfmt lint-shellcheck
        shell: bash

  gha:
    permissions:
      contents: read
    uses: ./.github/workflows/gha.yml

  renovate:
    permissions:
      contents: read
    uses: ./.github/workflows/renovate.yml
    with:
      files: default.json .github/renovate.json

  security:
    permissions:
      contents: read
    uses: ./.github/workflows/security.yml
