name: Lint GitHub Actions workflows

on:
  workflow_call:

jobs:
  actionlint:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 5
    env:
      ACTIONLINT_VERSION: v1.7.11
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        id: cache
        with:
          path: /usr/local/bin/actionlint
          key: actionlint-${{ env.ACTIONLINT_VERSION }}-${{ runner.os }}-${{ runner.arch }}

      - name: Download actionlint
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          bash <(curl "https://raw.githubusercontent.com/rhysd/actionlint/refs/tags/${ACTIONLINT_VERSION:?}/scripts/download-actionlint.bash")
          cp ./actionlint /usr/local/bin/actionlint
        shell: bash

      - name: Run actionlint
        run: actionlint -color
        shell: bash

  ghalint:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 5
    env:
      GHALINT_VERSION: v1.5.5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        id: cache
        with:
          path: /usr/local/bin/ghalint
          key: ghalint-${{ env.GHALINT_VERSION }}-${{ runner.os }}-${{ runner.arch }}

      - name: Download ghalint
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          asset="ghalint_${GHALINT_VERSION#v}_linux_amd64.tar.gz"

          gh release download "${GHALINT_VERSION:?}" \
            -R suzuki-shunsuke/ghalint \
            -p "${asset}"

          gh attestation verify "${asset}" \
            -R suzuki-shunsuke/ghalint \
            --signer-workflow suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml
          tar xvzf "${asset}" ghalint

          cp ./ghalint /usr/local/bin/ghalint
        shell: bash

      - name: Run ghalint
        run: ghalint run
        shell: bash
